services:
  api:
    container_name: api
    build:
      context: . 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
