# Generated by Django 4.2 on 2025-01-29 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.enterprise"
            ),
        ),
    ]
